### ISSUE TITLE
AlbumArt not fetched in android 10 devices

### ISSUE THREAD

**Issue by suranju** [sc4v3ng3r/flutter_audio_query#13]
the albumart property of the audio query returns null in android 10 devices, while it works fine in android 9.

**Comment by athul-ain** [comment]
Hope the Developer will Fix this soon

**Comment by sc4v3ng3r** [comment]
@suranju I am working in a Plugin refactor and I am aware about this issue. 
Appears to be not possible access album artwork in the new Android API 29+. I need figure out how to handle it and will be done soon.

As a quick fix you can try add the following line in Manifest file:
   `
<application
            android:requestLegacyExternalStorage="true"
`

**Comment by athul-ain** [comment]
You can refer https://joebirch.co/2019/10/09/media-store-access-using-openfile-on-android-10/ if required

**Comment by athul-ain** [comment]
<application android:requestLegacyExternalStorage="true"
This doesn't seems to be working for me

**Comment by sc4v3ng3r** [comment]
I am closing because it's related to #21
