### ISSUE TITLE
Embedding V2

### ISSUE THREAD

**Issue by mvarendorff** [sc4v3ng3r/flutter_audio_query#14]
Since Flutter version 1.12 there is a [new mechanism](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration) for invoking plugins for Flutter Android applications. Are there plans to make this plugin compatible with v2 embedding? Missing support could be the reason for [issues in my current project](https://stackoverflow.com/q/60203223/6707985) which is mainly the reason I am asking.

I would love to help but I am
1. Not a lot into the inner workings of this project and
2. Have no clue how to properly set up this project so I can edit it with full autocompletion support.

If you could help me with 2 I can see what I can do adapting the plugin (unless you already started on it).

**Comment by sc4v3ng3r** [comment]
Hey buddy, thanks a lot for your feed back!

I'll provide this new Flutter plugin interface in this plugin I think I can do a quick fix today yet.

**Comment by sc4v3ng3r** [comment]
Hello @geisterfurz007 Could you please check the plugin version ```flutter_audio_query: ^0.3.4+1```.

**Comment by mvarendorff** [comment]
Yup, just did! Unfortunately the change does not fix my problem but as that wasn't point of this issue, I am closing this! Thanks for the update!
