### ISSUE TITLE
Target of URI doesn't exist: 'package:flutter_audio_query/flutter_audio_query.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

### ISSUE THREAD

**Issue by casual-coder-25** [sc4v3ng3r/flutter_audio_query#2]
New project. Tried your plugin but plugin not importing. tried everything in stackoverflow.
"Target of URI doesn't exist: 'package:flutter_audio_query/flutter_audio_query.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist."

**Comment by sc4v3ng3r** [comment]
Did you using the latest version in your pubspec file? 
` flutter_audio_query: ^0.2.1 `

**Comment by sc4v3ng3r** [comment]
I will close it because there is no more feedback and the plugin was tested and it's working fine.

**Comment by casual-coder-25** [comment]
yes latest one. I will try reinstalling. thank you
