### ISSUE TITLE
failed to cast String to bool for isMusic function in SongInfo class

### ISSUE THREAD

**Issue by mdarifmustafa** [sc4v3ng3r/flutter_audio_query#3]
I am using this version flutter_audio_query: ^0.2.1

and failed to check the SongInfo object object.isMusic due to below said error

> E/flutter (23006): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'String' is not a subtype of type 'bool'
> E/flutter (23006): #0      SongInfo.isMusic (package:flutter_audio_query/src/song_info.dart:55:23)

hope it will help to make this function mature.

**Comment by sc4v3ng3r** [comment]
Thanks for your feedback. It will be fixed on next path.

**Comment by sc4v3ng3r** [comment]
fixed [here](https://github.com/sc4v3ng3r/flutter_audio_query/commit/04668fcef1f6215f6101bbb51e459845f98e36f5)
