### ISSUE TITLE
Android 10 null album art issue

### ISSUE THREAD

**Issue by mahadydev** [sc4v3ng3r/flutter_audio_query#30]
Hi , 

Any active development happening in this package? I could use some help here. My audio player works file on <android9 but not in 10. I am not getting album art path , its returning null. Any solve or work around?

Thanks

**Comment by shayan4shayan** [comment]
#21 
issue is duplicated.

**Comment by sc4v3ng3r** [comment]
I am closing this issue due #21.The support for this plugin will start this week.
