### ISSUE TITLE
Is there any way we can get selected audio files. Since audioQuery.getSongs();  gives all audio files from the device.? 

### ISSUE THREAD

**Issue by pspatel602** [sc4v3ng3r/flutter_audio_query#44]
List<SongInfo> songs = await audioQuery.getSongs();  gives all the songs containing in the device. But what if when we want only selected songs from the device not all. 
For example Audiobook Player app in which when user select perticular song from the device only that songs should be loaded on the screen. So my question is that  there is any way that we can fetch only selected songs from the device only?

**Comment by sc4v3ng3r** [comment]
@pspatel602 If you want to pick specific songs the api provides ```getSongsById``` method.
You can check it right [here](https://pub.dev/documentation/flutter_audio_query/latest/flutter_audio_query/FlutterAudioQuery/getSongsById.html). I hope it helps.

**Comment by pspatel602** [comment]
What type of List<String> passed in  getSongsById() methods parameter . I mean we need to pass List of audio file paths or something else?
I am using file_picker to select audio files and store selected audio files path in a list.
Could you give an example how we can use getSongsById() method please?

**Comment by sc4v3ng3r** [comment]
@pspatel602 as the method name says getSongsBy**Id** you must pass a list with ids of the songs you want to fetch more details. The flutter_audio_query plugin doesn't provide a way to read song details from file paths yet but it could be something to be added.
