### ISSUE TITLE
Getting null in albumArtwork for all songs

### ISSUE THREAD

**Issue by lianulloa** [sc4v3ng3r/flutter_audio_query#62]
Hi! I am using this plugin to get all the music in my device, which is running Android 11, and I can't get the albumArtWork related to each song.

I'm getting songs using this `FlutterAudioQuery().getSongs()` but every song has null in this field

I guess, from this issue https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/283, that this is not happening for earlier versions of Android.

Can you help me? @sc4v3ng3r

**Comment by lianulloa** [comment]
I know songs got albumArt because I can see them with Phonograph

**Comment by lianulloa** [comment]
I have no idea of native code but maybe this can help to fix the bug in the plugin https://developer.android.com/reference/android/provider/MediaStore.Audio.AlbumColumns#ALBUM_ART
Here it says how this should be gotten

**Comment by sc4v3ng3r** [comment]
There is a different approach to handle android API 29+.

You can use [this](https://pub.dev/documentation/flutter_audio_query/latest/flutter_audio_query/FlutterAudioQuery/getArtwork.html) method to get the a raw image based on artist, album or song.

You can see the usage in [this section](https://github.com/sc4v3ng3r/flutter_audio_query/blob/master/README.md#getting-artwork-on-android--q) from the [README](https://github.com/sc4v3ng3r/flutter_audio_query/blob/master/README.md#flutter-audio-query) file.

**Comment by lianulloa** [comment]
So true @sc4v3ng3r , thank you very much and sorry for no reading enough of the Readme file and searching to much in google 😅
