### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by codearemo** [sc4v3ng3r/flutter_audio_query#7]
Hello, please I'm in here fairly new to most of the concepts used in this project. All I want to build is a music player. But the example here only fetches all the files but doesn't have a play feature.
I'd appreciate if there were resources you could recommend so I can fetch all the audio files on the device. Just like in your example project.
Thanks

**Comment by sc4v3ng3r** [comment]
Yes. Flutter audio query plugin only queries the data about audio media
including mp3 files path. I can use some type of AudioPlayer plugin to play
audio files.

There a lot of audio players packages on dart pub with them you can play
the songs that you queried with audio query plugin.

Em qui, 21 de nov de 2019 13:30, Omosipe Busola <notifications@github.com>
escreveu:

**Comment by codearemo** [comment]
Yes...Thank you. I now understand it better.
